"""lesson recordings: users.workspace_email, lesson_recordings, missing_recording_logs

Revision ID: rec1_lesson_recordings
Revises: gpk1_group_pay_kind
Create Date: 2026-09-10

Schema for the Google Meet lesson-recording pipeline (spec §4.3-§4.6).

Written by hand rather than autogenerated: autogenerate runs against the live database
and, on this project, reliably picks up unrelated drift from models that were created by
``create_all()`` and never migrated. Everything here is additive — three new nullable
columns/tables, no backfill, no rewrite of an existing table — so it is safe to apply
while the app is serving.
"""
from alembic import op
import sqlalchemy as sa


revision = "rec1_lesson_recordings"
down_revision = "gpk1_group_pay_kind"
branch_labels = None
depends_on = None


def upgrade():
    # The Workspace identity of a member of staff who hosts recorded lessons. Nullable
    # on purpose: its absence is the per-teacher rollout switch, so an unmigrated or
    # not-yet-onboarded teacher simply never gets a Meet link.
    op.add_column("users", sa.Column("workspace_email", sa.String(), nullable=True))
    op.create_index("ix_users_workspace_email", "users", ["workspace_email"])

    op.create_table(
        "lesson_recordings",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("event_id", sa.Integer(),
                  sa.ForeignKey("events.id", ondelete="CASCADE"), nullable=False),
        sa.Column("conference_record", sa.String(), nullable=True),
        sa.Column("drive_file_id", sa.String(), nullable=True),
        sa.Column("shared_drive_file_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False, server_default="pending"),
        sa.Column("hls_url", sa.String(), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column("ingested_at", sa.DateTime(), nullable=True),
        sa.Column("drive_purged_at", sa.DateTime(), nullable=True),
        sa.UniqueConstraint("event_id", name="uq_lesson_recording_event"),
    )
    op.create_index("ix_lesson_recording_status", "lesson_recordings", ["status"])
    # Partial unique: a Drive file may be ingested at most once, but many rows sit with
    # drive_file_id NULL while pending, and those must not collide with each other.
    op.create_index(
        "uq_lesson_recording_drive_file", "lesson_recordings", ["drive_file_id"],
        unique=True, postgresql_where=sa.text("drive_file_id IS NOT NULL"),
    )

    op.create_table(
        "missing_recording_logs",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("event_id", sa.Integer(),
                  sa.ForeignKey("events.id", ondelete="CASCADE"), nullable=False),
        sa.Column("teacher_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("detected_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.UniqueConstraint("event_id", name="uq_missing_recording_event"),
    )
    op.create_index("ix_missing_recording_teacher", "missing_recording_logs", ["teacher_id"])
    op.create_index("ix_missing_recording_resolved", "missing_recording_logs", ["resolved_at"])


def downgrade():
    op.drop_index("ix_missing_recording_resolved", table_name="missing_recording_logs")
    op.drop_index("ix_missing_recording_teacher", table_name="missing_recording_logs")
    op.drop_table("missing_recording_logs")

    op.drop_index("uq_lesson_recording_drive_file", table_name="lesson_recordings")
    op.drop_index("ix_lesson_recording_status", table_name="lesson_recordings")
    op.drop_table("lesson_recordings")

    op.drop_index("ix_users_workspace_email", table_name="users")
    op.drop_column("users", "workspace_email")
