"""Deterministic parser for College Board Bluebook practice score reports.

No AI and no OCR. These PDFs are generated by College Board from a fixed template, so
the score fields sit in a predictable text structure and can be extracted with plain
regex against the embedded text layer. That matters: a probabilistic reader that is
usually right is worse than useless for a score that decides a student's progress
report, because you cannot tell the wrong answers from the right ones.

The parse is deliberately strict. Anything that is not recognisably a College Board
practice report, or whose sections do not sum to its stated total, is REJECTED rather
than guessed at - a silently mis-parsed score is worse than a refused upload.

Example of the text this reads (name redacted)::

    SAT Practice 7 April 19, 2025
    TOTAL SCORE
    920
    ...
    SECTION SCORES
    Reading and Writing
    720
    Score Range:
    200-800
    Math
    200
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import date, datetime
from typing import Optional

SAT_SECTION_MIN = 200
SAT_SECTION_MAX = 800
SAT_TOTAL_MIN = 400
SAT_TOTAL_MAX = 1600

# Practice tests College Board publishes in Bluebook.
BLUEBOOK_MIN_TEST_NUMBER = 4
BLUEBOOK_MAX_TEST_NUMBER = 11

# Only ~50 KB of text is ever needed; anything larger is not one of these reports.
MAX_PDF_BYTES = 10 * 1024 * 1024


class BluebookReportError(ValueError):
    """The upload is not a usable College Board practice score report.

    The message is shown to the student, so it must say what to do next rather than
    leak parser internals.
    """


@dataclass(frozen=True)
class BluebookReport:
    """Everything trusted from the PDF. Scores are never taken from the client."""

    test_number: int
    verbal_score: int      # "Reading and Writing" on the report
    math_score: int
    total_score: int
    report_date: Optional[date]
    student_name: Optional[str]

    @property
    def sections_sum_to_total(self) -> bool:
        return self.verbal_score + self.math_score == self.total_score


def extract_pdf_text(data: bytes) -> str:
    """Pull the text layer out of a PDF.

    Raises :class:`BluebookReportError` for anything that is not a readable PDF,
    including an image-only scan, which has no text layer to read.
    """
    if not data:
        raise BluebookReportError("The file is empty.")
    if len(data) > MAX_PDF_BYTES:
        raise BluebookReportError("The file is too large (maximum 10 MB).")
    # Magic bytes, not the filename or the browser-supplied content type.
    if not data.startswith(b"%PDF-"):
        raise BluebookReportError(
            "Only the official PDF score report from Bluebook is accepted. "
            "Screenshots and photos cannot be used."
        )

    try:
        from io import BytesIO

        from pypdf import PdfReader

        reader = PdfReader(BytesIO(data))
        text = "\n".join((page.extract_text() or "") for page in reader.pages)
    except BluebookReportError:
        raise
    except Exception as exc:  # pragma: no cover - defensive, pypdf raises many types
        raise BluebookReportError("This PDF could not be read. It may be corrupted.") from exc

    if not text.strip():
        raise BluebookReportError(
            "No text could be read from this PDF. Export the score report from "
            "Bluebook rather than scanning or photographing it."
        )
    return text


def _normalize(text: str) -> str:
    """Collapse horizontal whitespace but keep line structure, which the layout uses."""
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    text = re.sub(r"[ \t ]+", " ", text)
    return re.sub(r"\n{2,}", "\n", text)


_RE_HEADER = re.compile(
    r"SAT\s+Practice\s+(\d{1,2})\s+([A-Z][a-z]+\.?\s+\d{1,2},\s*\d{4})", re.IGNORECASE
)
_RE_TEST_ONLY = re.compile(r"SAT\s+Practice\s+(\d{1,2})", re.IGNORECASE)
_RE_TOTAL = re.compile(r"TOTAL\s+SCORE\s*\n\s*(\d{3,4})", re.IGNORECASE)
_RE_VERBAL = re.compile(r"Reading\s+and\s+Writing\s*\n\s*(\d{3})\s*\n\s*Score\s+Range", re.IGNORECASE)
_RE_MATH = re.compile(r"\bMath\s*\n\s*(\d{3})\s*\n\s*Score\s+Range", re.IGNORECASE)
_RE_NAME = re.compile(r"Name:\s*(.+)")

_DATE_FORMATS = ("%B %d, %Y", "%b %d, %Y", "%b. %d, %Y")


def _parse_report_date(raw: str) -> Optional[date]:
    cleaned = re.sub(r"\s+", " ", raw).strip()
    for fmt in _DATE_FORMATS:
        try:
            return datetime.strptime(cleaned, fmt).date()
        except ValueError:
            continue
    return None


def parse_report_text(text: str) -> BluebookReport:
    """Parse an already-extracted score report.

    Split from the PDF step so the rules can be tested on captured text without
    shipping a real student's PDF into the repository.
    """
    norm = _normalize(text)

    if "Practice" not in norm or "SCORE" not in norm.upper():
        raise BluebookReportError(
            "This does not look like a College Board practice score report."
        )

    header = _RE_HEADER.search(norm)
    if header:
        test_number = int(header.group(1))
        report_date = _parse_report_date(header.group(2))
    else:
        # Some exports wrap the header line; fall back to the test number alone rather
        # than rejecting an otherwise valid report over a missing date.
        only = _RE_TEST_ONLY.search(norm)
        if not only:
            raise BluebookReportError(
                "Could not find the practice test number on this report."
            )
        test_number = int(only.group(1))
        report_date = None

    if not (BLUEBOOK_MIN_TEST_NUMBER <= test_number <= BLUEBOOK_MAX_TEST_NUMBER):
        raise BluebookReportError(
            f"This report is for SAT Practice {test_number}, which is outside the "
            f"range {BLUEBOOK_MIN_TEST_NUMBER}-{BLUEBOOK_MAX_TEST_NUMBER}."
        )

    total_m = _RE_TOTAL.search(norm)
    verbal_m = _RE_VERBAL.search(norm)
    math_m = _RE_MATH.search(norm)
    if not (total_m and verbal_m and math_m):
        missing = [
            label for label, found in (
                ("total score", total_m), ("Reading and Writing", verbal_m), ("Math", math_m)
            ) if not found
        ]
        raise BluebookReportError(
            "Could not read the " + " and ".join(missing) + " from this report. "
            "Upload the score report exactly as Bluebook exported it."
        )

    total = int(total_m.group(1))
    verbal = int(verbal_m.group(1))
    math = int(math_m.group(1))

    for label, value in (("Reading and Writing", verbal), ("Math", math)):
        if not (SAT_SECTION_MIN <= value <= SAT_SECTION_MAX):
            raise BluebookReportError(
                f"The {label} score ({value}) is outside the valid range "
                f"{SAT_SECTION_MIN}-{SAT_SECTION_MAX}."
            )
    if not (SAT_TOTAL_MIN <= total <= SAT_TOTAL_MAX):
        raise BluebookReportError(
            f"The total score ({total}) is outside the valid range "
            f"{SAT_TOTAL_MIN}-{SAT_TOTAL_MAX}."
        )

    # The strongest integrity check available without contacting College Board: a
    # genuine report is always internally consistent, so a mismatch means either a
    # mis-parse or an edited file. Either way it must not be stored.
    if verbal + math != total:
        raise BluebookReportError(
            f"This report is inconsistent: {verbal} + {math} does not equal the stated "
            f"total of {total}. Please upload the original, unedited PDF."
        )

    name_m = _RE_NAME.search(norm)
    student_name = name_m.group(1).strip() if name_m else None
    if student_name:
        # The name sits on its own line, but a wrapped export can trail the next
        # sentence onto it; keep only the leading name-like part.
        student_name = re.split(r"\s{2,}|This practice", student_name)[0].strip() or None

    return BluebookReport(
        test_number=test_number,
        verbal_score=verbal,
        math_score=math,
        total_score=total,
        report_date=report_date,
        student_name=student_name,
    )


def parse_report_pdf(data: bytes) -> BluebookReport:
    """Extract and parse in one step. The only entry point callers should need."""
    return parse_report_text(extract_pdf_text(data))


def names_are_similar(pdf_name: Optional[str], account_name: Optional[str]) -> bool:
    """Loose comparison used to FLAG a mismatch for staff, never to block a submission.

    Deliberately permissive. A Kazakhstani student's College Board registration is
    routinely spelled differently from their LMS account - Latin vs Cyrillic, patronymic
    present or absent, given/family order swapped - so a strict check would lock out
    honest students far more often than it would catch a shared report. Any single
    shared name token counts as a match; staff review the rest.
    """
    if not pdf_name or not account_name:
        return True  # nothing to compare against: do not raise a false alarm

    def tokens(value: str) -> set[str]:
        return {t for t in re.split(r"[^\w]+", value.lower()) if len(t) > 2}

    a, b = tokens(pdf_name), tokens(account_name)
    if not a or not b:
        return True
    return bool(a & b)
